In [ ]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve

In [ ]:
df = pd.read_csv('https://gist.githubusercontent.com/tijptjik/9408623/raw/b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv')
df.head()

Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0     1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1     1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2     1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3     1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4     1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735

[5 rows x 14 columns]

In [ ]:
X = df.iloc[:,1:13]
Y = df.iloc[:,0]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [ ]:
scale = MinMaxScaler(feature_range = (0,1))

X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [ ]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
predictions = mlp.predict(X_test)
predictions

array([2, 2, 2, 2, 1, 2, 3, 3, 2, 2, 2, 2, 2, 3, 1, 2, 2, 1, 2, 2, 2, 1,
       2, 3, 1, 3, 1, 3, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 3, 1,
       2])

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix


print(confusion_matrix(y_test,predictions))

[[13  4  0]
 [ 0 18  0]
 [ 0  3  7]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      0.76      0.87        17
           2       0.72      1.00      0.84        18
           3       1.00      0.70      0.82        10

    accuracy                           0.84        45
   macro avg       0.91      0.82      0.84        45
weighted avg       0.89      0.84      0.85        45



In [ ]:
print ("Accuracy score = ", accuracy_score(y_test.to_numpy(), predictions.flatten()))

Accuracy score =  0.8444444444444444
